print("What is your Good Name?", end=' ')
name = input()
print("How old are you?", end=' ')
age = input()
print("How tall are you?", end=' ')
height = input()
print("How much do you weight?", end=' ')
weight = input()
print("*" * 20)

print(f"Hai {name}.")
print(f"So, you're {age} old, {height} tall and {weight} heavy.")
print(  )
print("$" * 50)
color = input("What color do you like?")
print(f"I like {color} color")
